os: Visual Studio 2015

version: 1.0.{build}

install:
- dnvm upgrade -r clr
- dnu restore

configuration: Release
platform: Any CPU

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg' 
  name: Nuget

test_script:
- cmd: >-
    dnx -p test\PolylineEncoder.Net.Tests\project.json test
